import test from 'node:test';
import assert from 'node:assert/strict';
import {activities,activityById,evaluate,optionsFor,contentFor} from '../src/shared/catalog.js';
import {newAttempt,transition,guidance,readProgress,recordSuccess,saveProgress,STORAGE_KEY,parseIntent,emptyProgress} from '../src/shared/learning.js';
import {referencesFor} from '../src/shared/references.js';
const memory=initial=>{const data={...initial};return {getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=v};};
test('Exactly four activities; ambiguous content is excluded without relabelling',()=>{assert.equal(activities.length,4);assert.ok(!activityById('materials').items.some(d=>d.id==='chalk'));assert.ok(!activityById('safety').items.some(d=>d.id==='insulating_tape_repair'));});
for(const a of activities){
 test(`${a.id}: each item accepts its supported answers only, no defaults`,()=>{for(const d of a.items){let s=newAttempt(d.id);assert.equal(s.choice,null);assert.equal(transition(a,s,{type:'submit'}),s);const answers=optionsFor(a,d).filter(o=>evaluate(a,d,o.id));assert.ok(answers.length);assert.equal(evaluate(a,d,'__proto__'),false);for(const o of optionsFor(a,d)){s=newAttempt(d.id);if(a.id==='conductors')s=transition(a,s,{type:'test'});s=transition(a,s,{type:'choose',choice:o.id});s=transition(a,s,{type:'submit'});assert.equal(s.phase==='success',evaluate(a,d,o.id));}}});
 test(`${a.id}: repeated success cannot inflate progress or attempts`,()=>{const d=a.items[0];let s=newAttempt(d.id);if(a.id==='conductors')s=transition(a,s,{type:'test'});s=transition(a,s,{type:'choose',choice:d.source||d.category});s=transition(a,s,{type:'submit'});let p=recordSuccess(emptyProgress(),a,s);for(let i=0;i<10;i++){s=transition(a,s,{type:'submit'});p=recordSuccess(p,a,s);}assert.equal(s.attempts,1);assert.equal(Object.keys(p.completed[a.id]).length,1);assert.equal(p.completed[a.id][d.id].assisted,false);});
 test(`${a.id}: hint escalation, wrong attempts and current-item guidance`,()=>{const d=a.items[0];let s=newAttempt(d.id);const wrong=optionsFor(a,d).find(o=>!evaluate(a,d,o.id));if(a.id==='conductors')s=transition(a,s,{type:'test'});s=transition(a,s,{type:'choose',choice:wrong.id});s=transition(a,s,{type:'submit'});assert.equal(s.phase,'retry');assert.equal(s.attempts,1);s=transition(a,s,{type:'hint'});assert.equal(guidance(a,s,'hint'),contentFor(a,d).hints[0]);s=transition(a,s,{type:'hint'});s=transition(a,s,{type:'hint'});assert.equal(guidance(a,s,'hint'),contentFor(a,d).explanation);assert.equal(s.revealed,true);s=transition(a,s,{type:'choose',choice:d.source||d.category});s=transition(a,s,{type:'submit'});assert.equal(recordSuccess(emptyProgress(),a,s).completed[a.id][d.id].assisted,true);const fresh=transition(a,s,{type:'select',id:a.items[1].id});assert.equal(fresh.choice,null);assert.equal(fresh.feedback,'');assert.ok(guidance(a,fresh).includes(a.items[1].label));});
 test(`${a.id}: learn mode and asking why do not reveal a new challenge`,()=>{const s=newAttempt(a.items[0].id);assert.ok(guidance(a,s,'why').includes('أولًا'));const learned=transition(a,s,{type:'mode',mode:'learn'});assert.equal(transition(a,learned,{type:'submit'}),learned);assert.equal(transition(a,learned,{type:'mode',mode:'play'}).revealed,true);});
 test(`${a.id}: reference identifiers are unique and correspond to actual items`,()=>{const refs=referencesFor(a);assert.equal(new Set(refs.map(r=>r.id)).size,refs.length);assert.ok(refs.every(r=>a.items.some(d=>d.id===r.id)));});
}
test('Conductors require observing the experiment before classifying',()=>{const a=activityById('conductors');let s=transition(a,newAttempt('ironNail'),{type:'choose',choice:'conductive'});assert.equal(transition(a,s,{type:'submit'}),s);s=transition(a,s,{type:'test'});assert.equal(transition(a,s,{type:'submit'}).phase,'success');});
test('Arabic intents normalize diacritics, hamza and alef maksura; unknown stays limited',()=>{assert.equal(parseIntent('أَعْطِنِي تَلْمِيحًا'),'hint');assert.equal(parseIntent('ماذا أفعل الآن؟'),'now');assert.equal(parseIntent('ليش؟'),'why');assert.equal(parseIntent('<img src=x onerror=alert(1)>'),'unknown');});
test('Corrupt and unavailable storage never blocks the activity',()=>{for(const value of ['{bad','null','[]','{"version":3,"completed":{"electricity":null}}'])assert.doesNotThrow(()=>readProgress(memory({[STORAGE_KEY]:value})));assert.deepEqual(readProgress({getItem(){throw Error();}}),emptyProgress());assert.equal(saveProgress({setItem(){throw Error();}},emptyProgress()),false);});
test('Old correct discoveries migrate and invalid entries are ignored',()=>{const p=readProgress(memory({'sharara-discoveries-v2':JSON.stringify({car:['battery','mains'],alien:['battery']}),'khabeer-materials-discoveries-v1':JSON.stringify({plasticRuler:'plastic',chalk:'wood',glassCup:'wood'}),'captain-safety-discoveries-v1':JSON.stringify({wet_hands_plug:'hazard'})}));assert.equal(Object.keys(p.completed.electricity).length,1);assert.equal(Object.keys(p.completed.materials).length,1);assert.ok(p.completed.safety.wet_hands_plug);});
test('Saved progress validates schema, valid IDs, resume location and assistance',()=>{const store=memory({[STORAGE_KEY]:JSON.stringify({version:3,completed:{electricity:{car:{assisted:false,attempts:1},fan:{assisted:'false',attempts:1},alien:{assisted:false,attempts:1}}},last:{activity:'javascript:',item:'car'}})});const p=readProgress(store);assert.deepEqual(Object.keys(p.completed.electricity),['car']);assert.equal(p.last,null);assert.equal(saveProgress(store,p),true);assert.deepEqual(readProgress(store),p);});
