import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const out='docs/implementation';await mkdir(out,{recursive:true});
const base=process.env.LAB_URL||'http://127.0.0.1:4173';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,permissions:['camera']});
const page=await context.newPage(),checks=[],errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));
page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(base))external.push(r.url());});
try{
 await page.goto(base+'/electricity.html?item=fan');await page.waitForFunction(()=>window.lab?.scene?.ready);
 await page.locator('[data-open=camera]').tap();await page.locator('#start-camera').tap();await page.waitForFunction(()=>document.querySelector('#camera-video').videoWidth>0);
 await page.evaluate(()=>window.testTrack=document.querySelector('#camera-video').srcObject.getVideoTracks()[0]);await page.locator('[data-close=camera]').tap();await page.waitForFunction(()=>testTrack.readyState==='ended');checks.push('Camera track stops immediately on close');
 await page.locator('[data-open=camera]').tap();await page.locator('#start-camera').tap();await page.waitForFunction(()=>document.querySelector('#camera-video').videoWidth>0);await page.locator('#capture-photo').tap();await expect(page.locator('#photo-preview')).toBeVisible();assert.equal(await page.evaluate(()=>lab.camera.stream),null);await expect(page.locator('#confirm-photo')).toBeDisabled();await page.locator('#manual-item').selectOption('washer');await page.locator('#confirm-photo').tap();await expect(page.locator('#scene')).toHaveAttribute('data-loaded','washer');checks.push('Capture, preview, stopped stream, manual confirmation and selected model');
 await page.locator('[data-open=camera]').tap();await page.locator('#photo-file').setInputFiles('assets/book/car.jpg');await expect(page.locator('#photo-preview')).toBeVisible();await expect(page.locator('#confirm-photo')).toBeDisabled();assert.equal(await page.evaluate(()=>lab.state.id),'washer');await page.locator('#match-photo').tap();await expect(page.locator('#manual-item')).toHaveValue('car',{timeout:60000});assert.equal(await page.evaluate(()=>lab.state.id),'washer');await page.screenshot({path:`${out}/camera-confirmation-mobile.png`,fullPage:true});await page.locator('#confirm-photo').tap();await expect(page.locator('#scene')).toHaveAttribute('data-loaded','car');checks.push('Real local book matching proposes car and requires child confirmation');
 await page.locator('[data-open=camera]').tap();await page.locator('#photo-file').setInputFiles({name:'invalid.png',mimeType:'image/png',buffer:Buffer.from('not a png')});await expect(page.locator('#camera-status')).toContainText('قراءة الصورة');await expect(page.locator('#confirm-photo')).toBeDisabled();
 const blank=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=320;c.height=240;const g=c.getContext('2d');g.fillStyle='white';g.fillRect(0,0,320,240);return c.toDataURL().split(',')[1];});await page.locator('#photo-file').setInputFiles({name:'blank.png',mimeType:'image/png',buffer:Buffer.from(blank,'base64')});await page.locator('#match-photo').tap();await expect(page.locator('#camera-status')).toContainText('لم أتعرف',{timeout:60000});await expect(page.locator('#confirm-photo')).toBeDisabled();await page.locator('[data-close=camera]').tap();checks.push('Unsupported/invalid and blank images never produce false success');
 await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=()=>Promise.reject(new DOMException('Denied','NotAllowedError'));});await page.locator('[data-open=camera]').tap();await page.locator('#start-camera').tap();await expect(page.locator('#camera-status')).toContainText('اختر العنصر');await page.locator('#manual-item').selectOption('fan');await page.locator('#confirm-photo').tap();await expect(page.locator('#scene')).toHaveAttribute('data-loaded','fan');checks.push('Camera denial leaves manual selection and activity fully usable');
 await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>{window.deliverCamera=resolve;});});await page.locator('[data-open=camera]').tap();await page.locator('#start-camera').tap();await page.locator('[data-close=camera]').tap();await page.evaluate(()=>{window.lateStopped=false;deliverCamera({getTracks:()=>[{stop:()=>window.lateStopped=true}]});});await page.waitForFunction(()=>window.lateStopped);checks.push('Late camera permission after closing cannot leave a live stream');
 const recognition=await page.evaluate(async()=>{
  const {recognize}=await import('/src/electricity/recognition.js');const {activities}=await import('/src/shared/catalog.js');const {referencesFor}=await import('/src/shared/references.js');const results=[];
  for(const [activityId,ids] of [['safety',['overloaded_socket','kids_playing_cords','baby_biting_cord','exposed_damaged_wire','inserting_scissors_socket']],['conductors',['metalSpoon','paperEnvelope','fabricCloth','ironNail','eraser','glassCup','chalk','woodStick','paperClip']]]){
   const activity=activities.find(a=>a.id===activityId),refs=referencesFor(activity);
   for(const id of ids){const ref=refs.find(r=>r.id===id),img=new Image();img.src=ref.source;await img.decode();const c=document.createElement('canvas');const [x,y,w,h]=ref.rect;c.width=w*2+40;c.height=h*2+40;const g=c.getContext('2d');g.fillStyle='white';g.fillRect(0,0,c.width,c.height);g.translate(c.width/2,c.height/2);g.rotate(.035);g.drawImage(img,x,y,w,h,-w,-h,w*2,h*2);const match=await recognize(c.toDataURL(),refs);results.push({activity:activityId,id,matched:match?.id||null});}
  }
  const img=new Image();img.src='/assets/book/washer.jpg';await img.decode();const c=document.createElement('canvas');c.width=500;c.height=500;const g=c.getContext('2d');g.fillStyle='white';g.fillRect(0,0,500,500);g.translate(250,250);g.rotate(.12);g.drawImage(img,-img.width,-img.height,img.width*2,img.height*2);const rotated=await recognize(c.toDataURL());
  return {results,rotated:rotated?.id||null};
 });
 assert.equal(recognition.rotated,'washer');for(const r of recognition.results)assert.ok(r.matched===r.id||r.matched===null,`False match: ${JSON.stringify(r)}`);assert.ok(recognition.results.filter(r=>r.matched).length>=10);checks.push('Rotated/scaled electricity reference and 14 cropped page fixtures; no false IDs');
 const audio=await page.evaluate(async()=>{
  lab.audio.stop();const synthOriginal=window.speechSynthesis,utteranceOriginal=window.SpeechSynthesisUtterance;
  const fake=new EventTarget();let voices=[],spoken=[];fake.getVoices=()=>voices;fake.cancel=()=>{};fake.speak=u=>{spoken.push(u.text);u.onend?.();};
  Object.defineProperty(window,'speechSynthesis',{configurable:true,value:fake});window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};
  try{const {AudioManager}=await import('/src/shared/audio-manager.js');const statuses=[];const manager=new AudioManager(s=>statuses.push(s));manager.configure({mode:'device'});manager.enabled=true;manager.unlocked=true;
   const old=manager.speak('old fixture');manager.stop();const latest=manager.speak('current fixture');setTimeout(()=>{voices=[{lang:'ar-SA',localService:true}];fake.dispatchEvent(new Event('voiceschanged'));},40);await Promise.all([old,latest]);const delayed=spoken.join(',')==='current fixture';
   voices=[{lang:'ar-SA',localService:false}];await manager.speak('remote must not run');const remoteBlocked=!spoken.includes('remote must not run')&&statuses.at(-1)==='unavailable';manager.stop();return {delayed,remoteBlocked};
  }finally{Object.defineProperty(window,'speechSynthesis',{configurable:true,value:synthOriginal});window.SpeechSynthesisUtterance=utteranceOriginal;}
 });assert.equal(audio.delayed,true);assert.equal(audio.remoteBlocked,true);checks.push('Delayed Arabic voices load; stale narration is canceled; remote TTS voice is rejected');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await writeFile(`${out}/camera-results.json`,JSON.stringify({checks,recognition,audio,errors,external,limits:['Camera stream is synthetic, not a physical camera. Matching tested on known scans transformed in browser; lighting, printed-page glare and real phone focus remain unverified.']},null,2));console.log(JSON.stringify({checks,recognition,audio,errors,external},null,2));
}finally{await browser.close();}

