import {readFile,writeFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const entries=[
 {id:'original-models',files:['src/scene.js','assets/models/lab-design.json'],sourcePage:null,creator:'Original artwork created for Sharara Lab',license:'CC0-1.0',licenseFile:'licenses/ORIGINAL-ASSETS-CC0.txt',format:'Procedural JavaScript Three.js geometry + JSON',models:['single-cell toy car','single-cell portable radio','home refrigerator with hinged door','AA ordinary cell','wheeled lab cart','science room','Sharara robot'],downloaded:false,original:true,permissions:{use:true,modify:true,redistribute:true,attributionRequired:false},triangles:null,geometryNote:'Complete initial scene measured at 32616 triangles; per-model counts not separately measured. Geometry regenerated locally; no downloaded GLB claimed.'},
 {id:'original-interface',files:['src/icons.js','public/favicon.svg'],sourcePage:null,creator:'Original artwork created for Sharara Lab',license:'CC0-1.0',licenseFile:'licenses/ORIGINAL-ASSETS-CC0.txt',format:'SVG',downloaded:false,original:true,permissions:{use:true,modify:true,redistribute:true,attributionRequired:false}},
 {id:'original-audio',files:['src/audio.js'],sourcePage:null,creator:'Original short synthesized phrase for Sharara Lab',license:'CC0-1.0',licenseFile:'licenses/ORIGINAL-ASSETS-CC0.txt',format:'Web Audio oscillator synthesis',downloaded:false,original:true,permissions:{use:true,modify:true,redistribute:true,attributionRequired:false}},
 {id:'three',files:['vendor/three.module.js','vendor/three.core.min.js','vendor/addons/geometries/RoundedBoxGeometry.js'],sourcePage:'https://github.com/mrdoob/three.js/tree/r180',creator:'Three.js authors and contributors',version:'0.180.0',license:'MIT',licenseFile:'licenses/THREE-MIT.txt',format:'ES modules',downloaded:true,downloadMethod:'npm package three@0.180.0; required files vendored locally',permissions:{use:true,modify:true,redistribute:true,attributionRequired:true},modifications:'three.module.min.js copied as three.module.js; source content unmodified'},
 {id:'tajawal',files:['assets/fonts/tajawal-arabic-400-normal.woff2','assets/fonts/tajawal-arabic-700-normal.woff2','assets/fonts/tajawal-latin-400-normal.woff2','assets/fonts/tajawal-latin-700-normal.woff2'],sourcePage:'https://fontsource.org/fonts/tajawal',creator:'Google Inc., copyright per packaged license',version:'@fontsource/tajawal 5.2.6',license:'OFL-1.1',licenseFile:'licenses/TAJAWAL-OFL.txt',format:'WOFF2',downloaded:true,downloadMethod:'npm package @fontsource/tajawal@5.2.6',permissions:{use:true,modify:true,redistribute:true,attributionRequired:true},modifications:'None; four unmodified supplied subsets selected'}
];
entries.push(
 {id:'kenney-book-models',files:(await readdir('assets/models/book')).map(f=>'assets/models/book/'+f),creator:'Kenney',license:'CC0-1.0',sourcePage:'https://github.com/Hidencod/tge-assets',originalPacks:['https://kenney.nl/assets/furniture-kit','https://kenney.nl/assets/car-kit','https://kenney.nl/assets/city-kit-roads'],downloaded:true,format:'GLB',details:'Seven actual downloaded models; see ATTRIBUTIONS.md for exact mapping.'},
 {id:'opencv',files:['vendor/opencv.js'],creator:'OpenCV contributors',license:'Apache-2.0',licenseFile:'licenses/OPENCV-APACHE-2.0.txt',sourcePage:'https://docs.opencv.org/4.13.0/opencv.js',downloaded:true,version:'4.13.0'},
 {id:'three-addons-redesign',files:['vendor/addons/controls/OrbitControls.js','vendor/addons/loaders/GLTFLoader.js','vendor/addons/utils/BufferGeometryUtils.js'],creator:'Three.js contributors',license:'MIT',licenseFile:'licenses/THREE-MIT.txt',downloaded:true},
 {id:'book-references',files:(await readdir('assets/book')).map(f=>'assets/book/'+f),creator:'User-supplied textbook illustrations',license:'Original textbook rights retained; not CC0',downloaded:false,format:'JPEG crops',purpose:'Local reference matching'},
 {id:'arabic-guide-recordings',files:(await readdir('assets/audio/electricity')).map(f=>'assets/audio/electricity/'+f),creator:'Original educational script; ar-SA-ZariyahNeural synthesis',license:'See provider voice terms; no CC0 claim',downloaded:false,generated:true,format:'MP3 + transcript JSON'},
 {id:'model-thumbnails',files:(await readdir('assets/thumbnails')).map(f=>'assets/thumbnails/'+f),creator:'Local renders of Kenney/original models',license:'CC0-1.0',format:'PNG',generated:true},
 {id:'redesign-original-artwork',files:['src/electricity/models.js','src/electricity/icons.js'],creator:'Original educational geometry, effects, icons and mascot',license:'CC0-1.0',licenseFile:'licenses/ORIGINAL-ASSETS-CC0.txt',original:true}
);
for(const e of entries){e.localFiles=[];for(const path of e.files){const bytes=await readFile(path);e.localFiles.push({path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}e.totalBytes=e.localFiles.reduce((a,f)=>a+f.bytes,0);delete e.files;}
await writeFile('ASSET_MANIFEST.json',JSON.stringify({schemaVersion:1,researchDate:'2026-10-07',runtimeNetwork:'Local files only',researchRecord:'docs/redesign/DESIGN.md',attributions:'ATTRIBUTIONS.md',assets:entries,rejectedCandidatePolicy:'Candidate pages and unverified metadata are recorded in the research document; no rejected model is included or claimed as downloaded.'},null,2)+'\n');
console.log('ASSET_MANIFEST.json written with sizes and SHA-256 hashes.');
