import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const entries=[
 {id:'original-models',files:['src/scene.js','assets/models/lab-design.json'],sourcePage:null,creator:'Original artwork created for Sharara Lab',license:'CC0-1.0',licenseFile:'licenses/ORIGINAL-ASSETS-CC0.txt',format:'Procedural JavaScript Three.js geometry + JSON',models:['single-cell toy car','single-cell portable radio','home refrigerator with hinged door','AA ordinary cell','wheeled lab cart','science room','Sharara robot'],downloaded:false,original:true,permissions:{use:true,modify:true,redistribute:true,attributionRequired:false},triangles:null,geometryNote:'Complete initial scene measured at 32616 triangles; per-model counts not separately measured. Geometry regenerated locally; no downloaded GLB claimed.'},
 {id:'original-interface',files:['src/icons.js','public/favicon.svg'],sourcePage:null,creator:'Original artwork created for Sharara Lab',license:'CC0-1.0',licenseFile:'licenses/ORIGINAL-ASSETS-CC0.txt',format:'SVG',downloaded:false,original:true,permissions:{use:true,modify:true,redistribute:true,attributionRequired:false}},
 {id:'original-audio',files:['src/audio.js'],sourcePage:null,creator:'Original short synthesized phrase for Sharara Lab',license:'CC0-1.0',licenseFile:'licenses/ORIGINAL-ASSETS-CC0.txt',format:'Web Audio oscillator synthesis',downloaded:false,original:true,permissions:{use:true,modify:true,redistribute:true,attributionRequired:false}},
 {id:'three',files:['vendor/three.module.js','vendor/three.core.min.js','vendor/addons/geometries/RoundedBoxGeometry.js'],sourcePage:'https://github.com/mrdoob/three.js/tree/r180',creator:'Three.js authors and contributors',version:'0.180.0',license:'MIT',licenseFile:'licenses/THREE-MIT.txt',format:'ES modules',downloaded:true,downloadMethod:'npm package three@0.180.0; required files vendored locally',permissions:{use:true,modify:true,redistribute:true,attributionRequired:true},modifications:'three.module.min.js copied as three.module.js; source content unmodified'},
 {id:'tajawal',files:['assets/fonts/tajawal-arabic-400-normal.woff2','assets/fonts/tajawal-arabic-700-normal.woff2','assets/fonts/tajawal-latin-400-normal.woff2','assets/fonts/tajawal-latin-700-normal.woff2'],sourcePage:'https://fontsource.org/fonts/tajawal',creator:'Google Inc., copyright per packaged license',version:'@fontsource/tajawal 5.2.6',license:'OFL-1.1',licenseFile:'licenses/TAJAWAL-OFL.txt',format:'WOFF2',downloaded:true,downloadMethod:'npm package @fontsource/tajawal@5.2.6',permissions:{use:true,modify:true,redistribute:true,attributionRequired:true},modifications:'None; four unmodified supplied subsets selected'}
];
for(const e of entries){e.localFiles=[];for(const path of e.files){const bytes=await readFile(path);e.localFiles.push({path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}e.totalBytes=e.localFiles.reduce((a,f)=>a+f.bytes,0);delete e.files;}
await writeFile('ASSET_MANIFEST.json',JSON.stringify({schemaVersion:1,researchDate:'2026-10-03',runtimeNetwork:'Local files only',researchRecord:'docs/asset-research.md',attributions:'ATTRIBUTIONS.md',assets:entries,rejectedCandidatePolicy:'Candidate pages and unverified metadata are recorded in the research document; no rejected model is included or claimed as downloaded.'},null,2)+'\n');
console.log('ASSET_MANIFEST.json written with sizes and SHA-256 hashes.');
