// ─── بنك الأجهزة الـ 24 الشامل ───
export const ALL_DEVICES = [
  // 12 جهاز بطارية جافة
  { id: 'car', name: 'سيارة الأطفال اللعبة', type: 'battery', icon: 'car', voltage: '1.5V - 3V', reason: 'تعمل ببطاريات جافة آمنة للأطفال تسمح لها بالحركة على الأرض بحرية.', wrongReason: 'لا تحتاج كهرباء رئيسية قوية! وصلها بمقبس الجدار خطر عليها وتكفيها بطارية آمنة.' },
  { id: 'radio', name: 'الراديو المحمول الصغير', type: 'battery', icon: 'radio', voltage: '3V', reason: 'صُمم للتنقل في الرحلات لذلك يستمد طاقته من البطاريات الجافة.', wrongReason: 'هذا راديو محمول صغير، البطارية الجافة تكفيه تماماً ولا يحتاج تياراً كبيراً.' },
  { id: 'flashlight', name: 'كشاف الجيب (الشعلة)', type: 'battery', icon: 'bolt', voltage: '1.5V', reason: 'يعتمد على البطارية الجافة ليعمل في أي مكان مظلم دون الحاجة لأسلاك.', wrongReason: 'كشاف الجيب مصمم ليكون محمولاً، الكهرباء الرئيسية تقيده والبطارية هي مصدره.' },
  { id: 'wallClock', name: 'ساعة الحائط الجدارية', type: 'battery', icon: 'refresh', voltage: '1.5V', reason: 'تعمل ببطارية جافة واحدة (AA) لتستمر بالحركة لأشهر طويلة على الحائط.', wrongReason: 'ساعة الحائط تستهلك طاقة ضئيلة جداً، يكفيها حجر بطارية واحد دون أسلاك.' },
  { id: 'remote', name: 'جهاز التحكم عن بُعد', type: 'battery', icon: 'settings', voltage: '3V (2xAAA)', reason: 'يعمل ببطاريتين جافتين صغيرتين (AAA) لسهولة حمله والتحكم بالشاشة.', wrongReason: 'ريموت التلفاز محمول في يدك، مقبس الجدار لا يناسبه إطلاقاً!' },
  { id: 'calculator', name: 'الآلة الحاسبة الإلكترونية', type: 'battery', icon: 'star', voltage: '1.5V', reason: 'تستهلك طاقة ضئيلة جداً وتكفيها بطارية جافة دائرية صغيرة للعمل.', wrongReason: 'الآلة الحاسبة تكتفي بخلية بطارية جافة خفيفة ولا تحتاج تياراً مستمراً.' },
  { id: 'digitalScale', name: 'الميزان الرقمي المنزلي', type: 'battery', icon: 'check', voltage: '3V', reason: 'يعمل ببطاريتين جافتين (AAA) ليتم وضعه ونقله على الأرضية بحرية دون أسلاك.', wrongReason: 'الميزان يحتاج إلى الأمان والحركة الحرة داخل الغرفة بدون سلك كهرباء.' },
  { id: 'smokeDetector', name: 'جهاز إنذار الدخان', type: 'battery', icon: 'shield', voltage: '9V', reason: 'يعمل ببطارية جافة (9V) ليبقى متيقظاً وينبهنا حتى لو انقطعت كهرباء المنزل!', wrongReason: 'إنذار الدخان يجب أن يظل يعمل بالبطارية حتى عند انقطاع كهرباء المنزل لسلامتنا.' },
  { id: 'laserPointer', name: 'مؤشر الليزر التعليمي', type: 'battery', icon: 'eye', voltage: '3V', reason: 'يستخدم بطاريات جافة دائرية صغيرة تتيح للمعلم التحرك والشرح بحرية.', wrongReason: 'مؤشر الليزر قلم محمول، الكهرباء الرئيسية غير مخصصة له.' },
  { id: 'hearingAid', name: 'سماعة الأذن الطبية', type: 'battery', icon: 'volume', voltage: '1.4V', reason: 'تعتمد على بطارية جافة دقيقة كحبة العدس لتعمل طوال اليوم داخل الأذن بأمان.', wrongReason: 'السماعة الطبية توضع داخل الأذن، ولا يمكن وصلها بالكهرباء الرئيسية للأمان!' },
  { id: 'robotToy', name: 'روبوت الألعاب الذكي', type: 'battery', icon: 'bolt', voltage: '4.5V (3xAA)', reason: 'لعبة أطفال متحركة تعمل ببطاريات جافة آمنة لتدوير محركاته وإضاءة عينيه بحرية.', wrongReason: 'ألعاب الأطفال صُممت لتعمل بالبطاريات الجافة الآمنة، ووصلها بمقبس الجدار خطر عليها جداً!' },
  { id: 'electricToothbrush', name: 'فرشاة الأسنان الكهربائية', type: 'battery', icon: 'refresh', voltage: '1.5V - 3V', reason: 'تستخدم بطارية جافة داخل مقبضها العازل لتدوير رأس الفرشاة بأمان تام قرب الماء.', wrongReason: 'استخدام كهرباء المنزل قرب مياه الحمام خطر شديد؛ لذلك تعمل ببطارية جافة آمنة ومعزولة.' },

  // 12 جهاز كهرباء رئيسية
  { id: 'fridge', name: 'الثلاجة المنزلية', type: 'mains', icon: 'fridge', voltage: '220V', reason: 'تعمل بمحرك تبريد ضخم يتطلب تيار 220 فولت مستمر من المقبس الجداري.', wrongReason: 'البطارية الجافة ضعيفة جداً! الثلاجة تحتوي على ضاغط تبريد ضخم يحتاج كهرباء رئيسية مستمرة.' },
  { id: 'microwave', name: 'فرن الميكروويف', type: 'mains', icon: 'home', voltage: '220V', reason: 'يحتاج تياراً كهرومائياً عالي الجهد لتوليد حرارة فورية، ولا تكفيه البطارية الصغيرة.', wrongReason: 'الميكروويف يولد حرارة عالية جداً تتعدى 1000 واط، البطارية الجافة تعجز عن ذلك تماماً!' },
  { id: 'washer', name: 'الغسالة الآلية', type: 'mains', icon: 'refresh', voltage: '220V', reason: 'تحتوي محركاً عملاقاً لتدوير الملابس وسحب المياه، وطاقتها من الكهرباء الرئيسية.', wrongReason: 'الغسالة تدير محركاً كبيراً ومضخات ماء، والبطارية الصغيرة لا تملك هذه القوة الكهربائية.' },
  { id: 'airConditioner', name: 'مكيف الهواء المنزلي', type: 'mains', icon: 'snow', voltage: '220V', reason: 'يستهلك قدرة كهربائية هائلة لتبريد الغرفة بأكملها ويحتاج مقبساً رئيسياً.', wrongReason: 'مكيف الهواء يسحب طاقة كهربائية عالية جداً لا يمكن توفيرها إلا عبر كهرباء المنزل.' },
  { id: 'vacuum', name: 'المكنسة الكهربائية', type: 'mains', icon: 'play', voltage: '220V', reason: 'تحتاج شفطاً هوائياً فائق القوة يستمد طاقته من سلك وقابس كهرباء المنزل.', wrongReason: 'محرك الشفط السريع يحتاج تياراً قوياً ومستمراً من مقبس الجدار.' },
  { id: 'lamp', name: 'مصباح المكتب السلكي', type: 'mains', icon: 'bolt', voltage: '220V', reason: 'موصول بسلك وقابس مباشر في جدار الغرفة للإنارة الدائمة دون استبدال بطاريات.', wrongReason: 'هذا المصباح مكتبي سلكي يعمل مباشرة بكهرباء المنزل 220V.' },
  { id: 'electricOven', name: 'الفرن الكهربائي المنزلي', type: 'mains', icon: 'home', voltage: '220V', reason: 'يحتاج طاقة حرارية هائلة تتعدى 2000 واط لطهي الطعام، ولا تكفيه البطارية.', wrongReason: 'الفرن يسخن لدرجات حرارة شديدة لصنع الطعام، وهذا يتطلب تيار كهرباء المنزل القوي.' },
  { id: 'iron', name: 'مكواة الملابس البخارية', type: 'mains', icon: 'shield', voltage: '220V', reason: 'توليد حرارة شديدة لكيّ الأقمشة يتطلب تياراً كهربائياً قوياً من قابس الجدار.', wrongReason: 'سخان المكواة يحول طاقة كهربائية ضخمة إلى حرارة، والبطارية لا تستطيع تشغيله.' },
  { id: 'hairDryer', name: 'مجفف الشعر (الاستشوار)', type: 'mains', icon: 'arrow', voltage: '220V', reason: 'يدمج بين محرك هواء سريع وسخان حراري جبار، ولا يعمل إلا بمقبس كهرباء المنزل.', wrongReason: 'الاستشوار يجمع بين الهواء الساخن والمروحة القوية، وهو بحاجة لكهرباء رئيسية.' },
  { id: 'electricWaterHeater', name: 'سخان الماء الكهربائي', type: 'mains', icon: 'plus', voltage: '220V', reason: 'يقوم بتسخين عشرات اللترات من الماء بقضيب تسخين ضخم متصل بكهرباء المنزل.', wrongReason: 'تسخين كميات كبيرة من المياه يتطلب تياراً عالي الشدة من الشبكة الرئيسية.' },
  { id: 'electricHeater', name: 'المدفأة الكهربائية الحرارية', type: 'mains', icon: 'plus', voltage: '220V', reason: 'تحتوي قضبان تسخين تشع حرارة هائلة لتدفئة الغرفة، وتستهلك تيار 220 فولت ضخماً.', wrongReason: 'تدفئة الغرفة تحتاج طاقة حرارية جبارة لا يمكن لأي بطارية جافة صغيرة توفيرها إطلاقاً!' },
  { id: 'blender', name: 'خلاط العصائر المنزلي', type: 'mains', icon: 'refresh', voltage: '220V', reason: 'يدير شفرات حادة فائقة السرعة لجرش الثلج والفواكه بقوة محرك كهربائي 220 فولت.', wrongReason: 'محرك الخلاط يحتاج عزم دوران هائل وسرعة فائقة من كهرباء المنزل لتقطيع وسحق الفواكه.' }
];

export const DEVICE_MAP = Object.fromEntries(ALL_DEVICES.map(d => [d.id, d]));

export function pickRandomDevices(count = 4) {
  const shuffled = [...ALL_DEVICES].sort(() => Math.random() - 0.5);
  const batteries = shuffled.filter(d => d.type === 'battery');
  const mains = shuffled.filter(d => d.type === 'mains');
  const picked = [batteries[0], batteries[1], mains[0], mains[1]].sort(() => Math.random() - 0.5);
  return picked.map(d => d.id);
}

export const config = {
  ageRange: [6, 9],
  defaultLanguage: 'ar',
  idleMs: 20000,
  contextMaxAgeMs: 120000,
  devices: pickRandomDevices(4)
};

export const deviceNames = {
  ar: Object.fromEntries(ALL_DEVICES.map(d => [d.id, d.name])),
  en: Object.fromEntries(ALL_DEVICES.map(d => [d.id, d.id]))
};

export const copy = {
  ar: {
    brand: 'مختبر شرارة',
    tagline: 'متحري مصادر الكهرباء والأجهزة',
    title: 'من أين تأتي الطاقة؟',
    subtitle: 'أجهزة متنوعة، بطارية جافة وكهرباء منزل... جرّب واكتشف!',
    lab: 'مختبر البطاريات والأجهزة المتحرك',
    start: 'ابدأ الاكتشاف',
    welcome: 'أهلًا يا مستكشف!',
    intro: 'أي جهاز يمكن أن يعمل بهذه البطارية أو الكهرباء الرئيسية؟ توقّع، جرّب، ثم لاحظ معي.',
    help: 'مساعدة',
    chat: 'اسأل شرارة',
    sound: 'الصوت',
    muted: 'الصوت مكتوم',
    reset: 'أجهزة جديدة',
    compare: 'دفتر اكتشافاتي',
    safety: 'نجرب هنا على الشاشة. كهرباء المنزل يتعامل معها شخص بالغ.',
    battery: 'البطارية الجافة',
    pick: 'اختر البطارية',
    remove: 'استعد البطارية',
    mains: 'كهرباء المنزل الرئيسية',
    demo: 'توصيل بالكهرباء الرئيسية',
    stopDemo: 'فصل الكهرباء الرئيسية',
    guide: 'اختر البطارية أو زر الكهرباء الرئيسية، ثم اختر الجهاز للتجربة.',
    dropGuide: 'ضع البطارية قرب الجهاز؛ سنركّبها في الحجرة المناسبة.',
    sourceNote: 'كل مصدر يزوّد الجهاز بالطاقة الكهربائية المناسبة لحجمه وتصميمه.',
    prediction: 'تتوقع أنه سيعمل بالبطارية؟',
    yes: 'نعم',
    no: 'لا',
    skip: 'سأجرّب وألاحظ',
    now: 'الحالة الآن',
    running: 'يعمل',
    off: 'متوقف',
    paused: 'متوقف مؤقتًا',
    discovered: 'ما اكتشفته',
    notYet: 'لم تجرّبه بعد',
    batteryFits: 'عمل بالبطارية الجافة',
    fridgeFact: 'البطارية غير مناسبة',
    mainsFact: 'عمل بالكهرباء الرئيسية',
    close: 'إغلاق',
    hint: 'تلميح',
    listen: 'استمع',
    stop: 'إيقاف الصوت',
    resetView: 'إعادة زاوية المشاهدة',
    inspect: 'تدوير وتفحص 3D',
    zoomIn: 'تقريب',
    zoomOut: 'إبعاد',
    cards: 'الأجهزة التفاعلية المعروضة',
    settings: 'إعدادات',
    motion: 'تقليل الحركة',
    language: 'اللغة',
    age: 'العمر المناسب',
    send: 'أرسل',
    ask: 'اكتب سؤالك هنا…',
    chatInfo: 'مساعد تعليمي بإجابات جاهزة تتغير مع التجربة.',
    challenge: 'تحدي المصادر',
    challengeIntro: 'اختر المصدر الذي شاهدت أنه يناسب كل جهاز.',
    explain: 'لماذا تختلف مصادر الأجهزة؟',
    explainGood: 'لأن لكل جهاز حاجة من الطاقة تناسب تصميمه',
    explainBad: 'لأن الحجم وحده يحدد المصدر',
    badge: 'مستكشف مصادر الطاقة',
    congrats: 'أحسنت الملاحظة والتجربة!',
    finish: 'أكمل الاكتشاف',
    next: 'تابع',
    confirm: 'نبدأ بأجهزة جديدة؟',
    confirmBody: 'سيتم اختيار 4 أجهزة عشوائية جديدة من بنك الأجهزة الـ 20 لتجربتها.',
    continue: 'متابعة جولتي',
    restart: 'أجهزة جديدة',
    tutorial: 'حرّك البطارية إلى الجهاز، أو اختر البطارية ثم انقر على اسم الجهاز، أو استخدم زر الكهرباء الرئيسية.',
    tutorialTitle:'طريقتان للتجربة',
    doneTutorial: 'فهمت، لنجرّب',
    skipTutorial: 'تخطَّ الشرح',
    robot: 'شرارة',
    robotRole: 'صديقك في المختبر',
    adultDemo: 'توصيل آمن بكهرباء المنزل الرئيسية يقوم به شرارة.',
    progress: 'اكتشافاتك',
    steps: ['أتوقّع', 'أجرّب', 'ألاحظ', 'أفسّر', 'أقارن'],
    power: 'جرّب التشغيل',
    door: 'افتح / أغلق الباب',
    cooling: 'تبريد يعمل',
    fallback: 'يمكنك تجربة النشاط بالبطاقات التفاعلية.',
    homeDrop: 'البطارية مكانها حجرة الجهاز المناسب.',
    symbolic: 'الخطوط والحركات تشرح الأثر؛ الكهرباء لا تُرى مباشرة.',
    activity: 'التجربة',
    available: 'جاهز للاستكشاف',
    quitHint: 'سأكمل وحدي'
  },
  en: {
    brand: 'Sharara Lab',
    tagline: 'Energy detective for grade 4',
    title: 'Where does power come from?',
    subtitle: 'Various devices, dry battery and mains electricity... try and explore!',
    lab: 'Battery & Devices Lab',
    start: 'Start exploring',
    welcome: 'Hello, explorer!',
    intro: 'Which device can this battery or mains electricity power? Predict, try, and observe.',
    help: 'Help',
    chat: 'Ask Sharara',
    sound: 'Sound on',
    muted: 'Sound off',
    reset: 'New devices',
    compare: 'My discoveries',
    safety: 'We experiment on screen. An adult handles household electricity.',
    battery: 'Battery',
    pick: 'Choose battery',
    remove: 'Return battery',
    mains: 'Mains Electricity',
    demo: 'Connect to Mains',
    stopDemo: 'Disconnect Mains',
    guide: 'Choose battery or mains electricity, then select a device.',
    dropGuide: 'Drop near a device; we place it in the proper compartment.',
    sourceNote: 'Each power source supplies electrical energy suited to device design.',
    prediction: 'Will this battery power it?',
    yes: 'Yes',
    no: 'No',
    skip: 'Try and observe',
    now: 'Right now',
    running: 'Running',
    off: 'Off',
    paused: 'Paused',
    discovered: 'What I discovered',
    notYet: 'Not explored yet',
    batteryFits: 'Ran on dry battery',
    fridgeFact: 'Battery does not fit',
    mainsFact: 'Ran on mains electricity',
    close: 'Close',
    hint: 'Hint',
    listen: 'Listen',
    stop: 'Stop audio',
    resetView: 'Reset view',
    inspect: 'Inspect device',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    cards: 'Active devices',
    settings: 'Settings',
    motion: 'Reduce motion',
    language: 'Language',
    age: 'Suggested age',
    send: 'Send',
    ask: 'Type your question…',
    chatInfo: 'An educational helper with prepared answers.',
    challenge: 'Power source challenge',
    challengeIntro: 'Choose the source you observed working with each device.',
    explain: 'Why do devices use different sources?',
    explainGood: 'Each device needs an energy supply suited to its design',
    explainBad: 'Size alone determines the source',
    badge: 'Power Source Explorer',
    congrats: 'Well observed and explored!',
    finish: 'Finish exploring',
    next: 'Continue',
    confirm: 'Try new devices?',
    confirmBody: '4 random devices from the 20-device bank will be loaded.',
    continue: 'Keep this round',
    restart: 'Load new devices',
    tutorial: 'Move battery to device or click battery then click device, or test mains.',
    tutorialTitle: 'How to explore',
    doneTutorial: 'Let’s try',
    skipTutorial: 'Skip guide',
    robot: 'Sharara',
    robotRole: 'Your lab companion',
    adultDemo: 'A safe demonstration by Sharara.',
    progress: 'Your discoveries',
    steps: ['Predict', 'Try', 'Observe', 'Explain', 'Compare'],
    power: 'Try power',
    door: 'Open / close',
    cooling: 'Cooling on',
    fallback: 'You can explore using the interactive cards.',
    homeDrop: 'Battery belongs in its device compartment.',
    symbolic: 'Lines and movement represent effects.',
    activity: 'Experiment',
    available: 'Ready to explore',
    quitHint: 'Keep exploring'
  }
};

export const messages = {
  start: ['لنكتشف مصدر طاقة هذه الأجهزة المعروضة! اختر البطارية أو الكهرباء الرئيسية.', 'Let’s discover the power sources of these devices!'],
  select: ['اختر البطارية أو الكهرباء الرئيسية ثم جرّبها مع هذا الجهاز.', 'Choose power source and try it with this device.'],
  pick: ['أنت تحمل البطارية الآن! ضعها في حجرة الجهاز المناسب أو انقر على اسمه.', 'Place battery into the matching device compartment.'],
  successBattery: ['أحسنت! هذا الجهاز يعمل بالبطارية الجافة الآمنة بنجاح.', 'Well done! This device runs on a dry battery.'],
  successMains: ['أحسنت! هذا الجهاز يحتاج طاقة قوية ومستمرة من الكهرباء الرئيسية.', 'Great! This device needs powerful mains electricity.'],
  wrongBattery: ['البطارية الجافة لا تناسب هذا الجهاز! إنه يحتاج كهرباء رئيسية قوية من مقبس الجدار.', 'A small battery cannot power this device; it needs mains electricity.'],
  wrongMains: ['انتبه! هذا الجهاز يعمل ببطارية جافة آمنة ولا نوصله بالكهرباء الرئيسية لحمايته.', 'Caution! This device uses safe dry batteries, not mains electricity.'],
  outside: ['لم تصل البطارية إلى مكانها بعد. جرّب قرب الجهاز أو اختره بالنقر.', 'Try dropping nearer to the device or click its name.'],
  cancel: ['عادت البطارية إلى الصينية. يمكنك المحاولة مجددًا.', 'The battery is back in the tray. You can try again.'],
  remove: ['توقف الجهاز لأن مصدر طاقته انفصل.', 'The device stopped because its power was removed.'],
  repeat: ['أكدت ملاحظتك مرة أخرى!', 'You confirmed your observation!'],
  match: ['توقعك وافق ما شاهدناه!', 'Your prediction matched!'],
  different: ['كانت النتيجة مختلفة عن توقعنا. هذا اكتشاف علمي جديد!', 'The result was different from prediction. A new discovery!'],
  stopMains: ['توقفت التغذية، فتوقف تشغيل الجهاز.', 'Power disconnected; device stopped.'],
  needsPower: ['الجهاز يحتاج مصدر طاقة مناسب أولاً.', 'The device needs a power source first.'],
  idle: ['هل تريد تلميحًا صغيرًا؟', 'Would you like a small hint?'],
  explored: ['أحسنت! اكتشفت مصادر طاقة جميع الأجهزة المعروضة. لنقارن النتائج!', 'You discovered the sources for all devices. Let’s compare!'],
  quizWrong: ['تذكر ما حدث عندما جرّبت هذا الجهاز. يمكنك المحاولة مجددًا.', 'Remember what happened. Try again.'],
  quizRight: ['إجابة ممتازة! هذه هي النتيجة العلمية التي لاحظناها.', 'Excellent! That matches our scientific observation.'],
  complete: ['مبارك يا بطل! أنهيت المهمة بنجاح واستحققت الوسام.', 'Congratulations! You earned the badge.'],
  asset: ['تم تجهيز شكل بديل؛ يمكنك متابعة التجربة.', 'Fallback ready; keep exploring.'],
  renderer: ['يمكنك تجربة النشاط بالبطاقات التفاعلية.', 'You can explore using the cards.'],
  chat: ['لنجرّب سؤالاً أو تلميحاً.', 'Try a question or hint.'],
  audio: ['يمكنك قراءة الرسالة ومشاهدة الحركة.', 'Read message and observe.'],
  homeDrop: ['البطارية مكانها حجرة الجهاز المناسب.', 'Battery belongs in device compartment.']
};

export const msg = (s, key) => messages[key]?.[s.language === 'en' ? 1 : 0] || key;
