import {config,copy,deviceNames,msg} from './config.js';
import {initialState,reducer,explorationDone,quizDone,validAction,nextActions} from './state.js';
import {answerQuestion,normalize} from './knowledge.js';
import {icon,robotSvg} from './icons.js';
import {stopAudio,radioTune,speak} from './audio.js';
let prefs={};try{prefs=JSON.parse(localStorage.getItem('sharara-preferences')||'{}');}catch{}
let state=initialState({...prefs,reducedMotion:prefs.reducedMotion??matchMedia('(prefers-reduced-motion: reduce)').matches});
let scene=null,seq=0,pendingDevice=null,drag=null,idleTimer=null,modalOpener=null,tutorial=false;
const history=[],counts=new Map(),app=document.querySelector('#app');
const $=s=>document.querySelector(s),t=()=>copy[state.language],name=id=>deviceNames[state.language][id];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function button(action,label,ico,cls='',extra=''){return `<button type="button" class="${cls}" data-action="${action}" ${extra}>${ico?icon(ico):''}<span>${label}</span></button>`;}
function shell(){const c=t();app.innerHTML=`
 <header class="header"><a class="brand" href="./" aria-label="${c.brand}"><span class="brand-mark">${icon('bolt')}</span><span><strong>${c.brand}</strong><small>${c.tagline}</small></span></a><nav class="top-actions" aria-label="${c.settings}">${button('help',c.help,'help','quiet')}${button('sound',state.muted?c.muted:c.sound,state.muted?'muted':'volume','quiet','id="sound-button"')}${button('settings',c.settings,'settings','icon-only')}</nav></header>
 <main><section class="heading"><div><span class="eyebrow">${c.lab}</span><h1>${c.title}<span class="title-spark">✧</span></h1><p>${c.subtitle}</p></div><div class="journey" aria-label="${c.steps.join('، ')}">${c.steps.map((s,i)=>`<span class="step ${i===1?'active':''}"><b>${icon(['eye','hand','eye','chat','book'][i])}</b>${s}</span>${i<4?'<i></i>':''}`).join('')}</div></section>
 <div class="lab-layout"><section class="workspace" aria-label="${c.activity}"><div class="scene-wrap"><div id="scene" role="img" aria-label="${c.lab}"></div><div class="scene-top"><span class="room-tag"><i></i>${c.available}</span><div class="camera-tools">${button('zoomIn',c.zoomIn,'plus','icon-only')}${button('zoomOut',c.zoomOut,'minus','icon-only')}${button('resetView',c.resetView,'refresh','icon-only')}</div></div><div id="scene-labels">${config.devices.map(id=>`<button class="scene-label" data-action="device" data-device="${id}" data-target="${id}" id="label-${id}">${name(id)}<span>○ ${c.off}</span></button>`).join('')}</div><div id="fallback-panel" hidden><div class="fallback-illustration">${icon('battery')}${icon('car')}${icon('radio')}${icon('fridge')}</div><h2>${c.fallback}</h2><p>${c.guide}</p></div><div class="scene-caption">${icon('hand')}<span id="scene-guide">${c.guide}</span></div><div id="intro" class="intro-card"><span class="intro-bolt">${icon('bolt')}</span><h2>${c.welcome}</h2><p>${c.intro}</p>${button('start',c.start,'arrow','primary')}</div><div id="tutorial" class="tutorial-card" hidden><div class="tutorial-path">${icon('battery')}<span>······</span>${icon('car')}</div><h2>${c.tutorialTitle}</h2><p>${c.tutorial}</p>${button('doneTutorial',c.doneTutorial,'check','primary')}${button('doneTutorial',c.skipTutorial,null,'text-button')}</div></div>
 <div class="experiment-tools"><div class="battery-tool"><button id="battery-button" data-action="pick" class="battery-button" aria-pressed="false"><span class="battery-drawing"><i></i><b>+</b><em>−</em></span><span><strong>${c.pick}</strong><small>AA · 1.5V</small></span>${icon('hand')}</button>${button('remove',c.remove,'refresh','text-button','id="remove-button" hidden')}</div><div class="tool-divider"></div><div class="mains-tool" data-target="mains">${icon('home')}<div><strong>${c.mains}</strong><small id="mains-caption">${c.adultDemo}</small></div>${button('mains',c.demo,'play','mains-button','id="mains-button"')}</div></div>
 <section class="device-list" aria-label="${c.cards}">${config.devices.map(id=>`<article class="device-card" id="card-${id}" data-target="${id}"><button data-action="device" data-device="${id}" class="device-main" aria-label="${name(id)}"><span class="device-icon ${id}">${icon(id)}</span><span><strong>${name(id)}</strong><small id="status-${id}">${c.now}: ${c.off}</small></span><span class="device-check" id="check-${id}">○</span></button><div class="device-controls">${button('inspect',c.inspect,'eye','text-button',`data-device="${id}"`)}${button('power',c.power,'play','icon-only',`data-device="${id}"`)}</div></article>`).join('')}</section><p class="source-note">${c.sourceNote}</p></section>
 <aside class="companion"><section class="robot-card"><div class="robot-card-head"><span><strong>${c.robot}</strong><small>${c.robotRole}</small></span><span class="online-dot"></span></div>${robotSvg}<div class="speech-bubble"><p id="message" role="status" aria-live="polite" aria-atomic="true">${c.intro}</p><div id="suggestions" class="suggestions"></div></div><div class="speech-controls">${button('listen',c.listen,'volume','text-button')}${button('stopAudio',c.stop,'pause','text-button')}</div>${button('chat',c.chat,'chat','chat-open','id="chat-toggle" aria-expanded="false"')}${button('hint',c.hint,'bolt','text-button')}</section><section class="discovery-card"><div><span class="small-icon">${icon('book')}</span><h2>${c.progress}</h2><span id="progress-count">0 / 4</span></div><div class="progress-track"><i id="progress-fill"></i></div><p id="progress-text">${c.notYet}</p>${button('compare',c.compare,'arrow','text-button','id="comparison-button"')}</section></aside></div>
 <footer><span>${icon('shield')}${c.safety}</span>${button('reset',c.reset,'refresh','text-button')}</footer></main>
 <aside id="chat-panel" hidden aria-label="${c.chat}"><div class="chat-heading"><span class="tiny-robot">${icon('bolt')}</span><div><strong>${c.robot}</strong><small>${c.robotRole}</small></div>${button('chat',c.close,'close','icon-only','id="chat-close"')}</div><div id="chat-history" role="log" aria-live="polite"></div><div class="quick-questions">${(state.language==='ar'?['ماذا أفعل؟','لماذا لم يعمل؟','هل البطارية فيها كهرباء؟']:['What do I do next?','Why is it off?','Does a battery have electricity?']).map(q=>button('quickQuestion',q,null,'question-chip',`data-question="${q}"`)).join('')}</div><form id="chat-form"><label class="sr-only" for="question">${c.ask}</label><input id="question" maxlength="600" autocomplete="off" placeholder="${c.ask}"/><button type="submit" class="primary icon-only" aria-label="${c.send}">${icon('send')}</button></form><p class="chat-info">${c.chatInfo}</p></aside>
 <dialog id="dialog"><div id="dialog-content"></div></dialog><div id="drag-ghost" hidden>${icon('battery')}</div>`;
 document.documentElement.lang=state.language;document.documentElement.dir=state.language==='ar'?'rtl':'ltr';
 $('#dialog').addEventListener('cancel',()=>{pendingDevice=null;if(state.batteryLocation==='held')dispatch({type:'CANCEL_DRAG'});});
 $('#dialog').addEventListener('close',()=>{modalOpener?.focus?.();});
 $('#chat-form').addEventListener('submit',e=>{e.preventDefault();ask($('#question').value);$('#question').value='';});
 $('#battery-button').addEventListener('pointerdown',batteryDown);
 render();
}
function dispatch(event){const old=state;state=reducer(state,{id:`${state.sessionRevision}:${++seq}`,sessionRevision:state.sessionRevision,...event});if(state===old)return;
 if(event.type==='RESET'){stopAudio();history.length=0;counts.clear();pendingDevice=null;drag=null;tutorial=false;$('#drag-ghost').hidden=true;scene?.reset();closeDialog();}
 if(state.muted||state.devices.radio.status!=='running'||event.type==='PICK_BATTERY')stopAudio();
 if(!state.muted&&state.devices.radio.status==='running'&&(old.devices.radio.status!=='running'||old.muted))playRadio();
 if(['SET_MUTED','SET_REDUCED_MOTION','SET_LANGUAGE','SET_AGE'].includes(event.type)){try{localStorage.setItem('sharara-preferences',JSON.stringify({muted:state.muted,reducedMotion:state.reducedMotion,language:state.language,ageRange:state.ageRange}));}catch{}}
 render();if(!['IDLE','CHAT_RESPONSE'].includes(event.type))resetIdle();
}
function resetIdle(){clearTimeout(idleTimer);const revision=state.sessionRevision;idleTimer=setTimeout(()=>dispatch({type:'IDLE',sessionRevision:revision}),config.idleMs);}
function actionLabel(a){const c=t();return a.id==='select_device'?`${state.language==='ar'?'جرّب':'Try'} ${name(a.device)}`:a.id==='show_mains_demo'?c.demo:a.id==='open_comparison'?c.compare:a.id==='restart'?c.reset:a.id==='pick_battery'?c.pick:c.hint;}
function actionsHTML(actions){return actions.filter(a=>validAction(state,a)).map(a=>`<button class="action-chip" data-action="suggested" data-suggestion="${escape(JSON.stringify(a))}">${escape(actionLabel(a))}${icon('arrow')}</button>`).join('');}
function render(){if(!$('#message'))return;const c=t();document.body.classList.toggle('reduced-motion',state.reducedMotion);document.body.classList.toggle('holding-battery',state.batteryLocation==='held');
 $('#intro').hidden=!['intro','loading','recoverable_error'].includes(state.phase);$('#tutorial').hidden=!tutorial;$('#intro button').disabled=state.phase==='loading';
 $('#message').textContent=state.phase==='intro'?c.intro:state.message||c.intro;
 $('#suggestions').innerHTML=state.phase==='exploring'?(state.messageKey==='idle'?button('hint',c.yes,'bolt','action-chip')+button('dismissHint',c.quitHint,null,'text-button'):actionsHTML(nextActions(state))):'';
 $('#sound-button').innerHTML=icon(state.muted?'muted':'volume')+`<span>${state.muted?c.muted:c.sound}</span>`;$('#sound-button').setAttribute('aria-pressed',String(!state.muted));
 const held=state.batteryLocation==='held';$('#battery-button').setAttribute('aria-pressed',String(held));$('#battery-button').classList.toggle('selected',held);$('#battery-button strong').textContent=held?(state.language==='ar'?'الآن اختر جهازًا':'Now choose a device'):c.pick;$('#battery-button').disabled=['intro','loading','recoverable_error'].includes(state.phase);
 $('#scene-guide').textContent=held?c.dropGuide:c.guide;$('#remove-button').hidden=['tray','held'].includes(state.batteryLocation);
 $('#mains-button').disabled=!state.discoveredFacts.includes('fridge_incompatible');$('#mains-button').innerHTML=icon(state.devices.fridge.status==='running'?'pause':'play')+`<span>${state.devices.fridge.status==='running'?c.stopDemo:c.demo}</span>`;
 for(const id of config.devices){const d=state.devices[id],found=state.exploredDevices.includes(id);$('#status-'+id).textContent=`${c.now}: ${c[d.status]}${d.source?' · '+(d.source==='battery'?c.battery:c.mains):''}`;$('#label-'+id+' span').textContent=(d.status==='running'?'● ':'○ ')+c[d.status];$('#card-'+id).classList.toggle('selected',state.selectedDevice===id);$('#card-'+id).classList.toggle('running',d.status==='running');$('#label-'+id).classList.toggle('running',d.status==='running');$('#check-'+id).innerHTML=found?icon('check'):'○';document.querySelectorAll(`[data-action="device"][data-device="${id}"]`).forEach(b=>{b.disabled=['intro','loading','recoverable_error'].includes(state.phase);b.setAttribute('aria-pressed',String(state.selectedDevice===id));});}
 $('#progress-count').textContent=`${state.discoveredFacts.length} / 4`;$('#progress-fill').style.width=`${state.discoveredFacts.length*25}%`;$('#progress-text').textContent=explorationDone(state)?msg(state,'explored'):state.exploredDevices.length?`${state.language==='ar'?'جرّبت':'Explored'} ${state.exploredDevices.length} / 3 ${state.language==='ar'?'أجهزة':'devices'}`:c.notYet;
 $('#comparison-button').disabled=!state.exploredDevices.length;
 const wasOpen=!$('#chat-panel').hidden;$('#chat-panel').hidden=!state.chatOpen;$('#chat-toggle').setAttribute('aria-expanded',String(state.chatOpen));if(state.chatOpen&&!wasOpen)setTimeout(()=>$('#question')?.focus(),0);
 $('#fallback-panel').hidden=state.rendererStatus!=='fallback';$('#scene-labels').hidden=state.rendererStatus==='fallback';if(state.rendererStatus==='fallback')$('#scene canvas')?.setAttribute('hidden','');
 if(state.chatOpen)renderChat();
}
function openDialog(html){modalOpener=document.activeElement;$('#dialog-content').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal();}
function closeDialog(){$('#dialog')?.close();}
function dialogHeader(title){return `<div class="dialog-heading"><h2>${title}</h2>${button('closeDialog',t().close,'close','icon-only')}</div>`;}
function tryDevice(id){if(state.batteryLocation!=='held'){dispatch({type:'SELECT_DEVICE',device:id});if(state.attemptsByDevice[id]===0)showPrediction(id,false);return;}
 if(state.attemptsByDevice[id]===0&&state.predictionByDevice[id]===null){showPrediction(id,true);return;}dispatch({type:'DROP_ON_DEVICE',device:id});}
function showPrediction(id,drop){pendingDevice={id,drop};openDialog(`${dialogHeader(name(id))}<div class="prediction-icon ${id}">${icon(id)}</div><h3>${t().prediction}</h3><p>${state.language==='ar'?'لا بأس إن كانت النتيجة مختلفة. التجربة تساعدنا لنتعلم.':'It is okay if the result differs. Experiments help us learn.'}</p><div class="dialog-actions">${button('predictYes',t().yes,null,'primary')}${button('predictNo',t().no,null,'secondary')}${button('predictSkip',t().skip,null,'text-button')}</div>`);}
function prediction(value){const p=pendingDevice;pendingDevice=null;if(!p)return;if(value!==null)dispatch({type:'PREDICT',device:p.id,value});closeDialog();if(p.drop)dispatch({type:'DROP_ON_DEVICE',device:p.id});}
function compare(){dispatch({type:'OPEN_COMPARISON'});const c=t();let html=`${dialogHeader(c.compare)}<p class="comparison-intro">${c.sourceNote}</p><div class="comparison-grid">${config.devices.map(id=>`<article>${icon(id)}<h3>${name(id)}</h3><small>${c.now}</small><strong>${c[state.devices[id].status]}${state.devices[id].source?' · '+(state.devices[id].source==='battery'?c.battery:c.mains):''}</strong><hr/><small>${c.discovered}</small><p>${state.discoveredFacts.includes(id+'_battery')?c.batteryFits:id==='fridge'&&state.discoveredFacts.includes('fridge_incompatible')?c.fridgeFact:c.notYet}${id==='fridge'&&state.discoveredFacts.includes('fridge_mains')?'<br/>'+c.mainsFact:''}</p></article>`).join('')}</div><p class="fine-print">${c.symbolic}</p>`;
 if(explorationDone(state))html+=`<section class="quiz"><h3>${c.challenge}</h3><p>${c.challengeIntro}</p>${config.devices.map(id=>`<div class="quiz-row"><strong>${name(id)} ${state.quiz[id]?icon('check'):''}</strong><div>${button('quiz',c.battery,'battery',state.quiz[id]&&(id!=='fridge')?'answer-correct':'secondary',`data-device="${id}" data-answer="battery"`)}${button('quiz',c.mains,'home',state.quiz[id]&&id==='fridge'?'answer-correct':'secondary',`data-device="${id}" data-answer="mains"`)}</div></div>`).join('')}<h3>${c.explain}</h3><div class="explanation-options">${button('quiz',c.explainGood,state.quiz.explanation?'check':null,state.quiz.explanation?'answer-correct':'secondary','data-device="explanation" data-answer="design"')}${button('quiz',c.explainBad,null,'secondary','data-device="explanation" data-answer="size"')}</div><p id="quiz-feedback" role="status">${['quizRight','quizWrong'].includes(state.messageKey)?state.message:''}</p>${button('complete',c.finish,'star','primary',quizDone(state)?'':'disabled')}</section>`;
 else html+=`<div class="dialog-actions">${button('closeDialog',c.continue,'arrow','primary')}</div>`;
 openDialog(html);}
function completed(){const c=t();openDialog(`${dialogHeader(c.congrats)}<div class="badge">${icon('star')}</div><h2 class="badge-title">${c.badge}</h2><p>${msg(state,'explored')}</p><div class="dialog-actions">${button('compare',c.compare,'book','primary')}${button('reset',c.reset,'refresh','secondary')}</div>`);}
function resetRequest(){if(!state.exploredDevices.length){dispatch({type:'RESET'});return;}openDialog(`${dialogHeader(t().confirm)}<p>${t().confirmBody}</p><div class="dialog-actions">${button('confirmReset',t().restart,'refresh','primary')}${button('closeDialog',t().continue,null,'secondary')}</div>`);}
function settings(){openDialog(`${dialogHeader(t().settings)}<label class="setting-row">${t().language}<select id="language"><option value="ar" ${state.language==='ar'?'selected':''}>العربية</option><option value="en" ${state.language==='en'?'selected':''}>English</option></select></label><label class="setting-row">${t().motion}<input type="checkbox" id="reduced-motion" ${state.reducedMotion?'checked':''}/></label><label class="setting-row">${t().age}<select id="age"><option value="standard" ${state.ageRange[0]===6?'selected':''}>6–9</option><option value="younger" ${state.ageRange[0]===4?'selected':''}>4–6 · ${state.language==='ar'?'مع بالغ':'with an adult'}</option></select></label><p class="fine-print">${t().chatInfo}</p>`);$('#reduced-motion').onchange=e=>dispatch({type:'SET_REDUCED_MOTION',value:e.target.checked});$('#age').onchange=e=>dispatch({type:'SET_AGE',value:e.target.value});$('#language').onchange=async e=>{const language=e.target.value;closeDialog();dispatch({type:'SET_LANGUAGE',value:language});scene?.dispose();scene=null;shell();await loadScene();};}
function renderChat(){const c=t();$('#chat-history').innerHTML=history.map(h=>`<div class="chat-bubble ${h.role}"><strong>${h.role==='user'?(state.language==='ar'?'أنت':'You'):c.robot}</strong><p>${escape(h.text)}</p>${h.response&&h===history.at(-1)?`<div class="suggestions">${actionsHTML(h.response.suggestedActions)}</div>`:''}</div>`).join('')||`<div class="chat-bubble assistant"><p>${c.intro}</p></div>`;$('#chat-history').scrollTop=$('#chat-history').scrollHeight;}
function ask(q){dispatch({type:'ASK_QUESTION'});const key=normalize(q),repeat=counts.get(key)||0;counts.set(key,repeat+1);try{const r=answerQuestion(q,state,{repeat});dispatch({type:'CHAT_RESPONSE',response:r});history.push({role:'user',text:String(q).slice(0,600)},{role:'assistant',text:r.text,response:r});if(history.length>30)history.splice(0,2);renderChat();}catch{dispatch({type:'CHAT_FAILED'});}}
function runSuggested(a){if(!validAction(state,a))return;if(a.id==='select_device')tryDevice(a.device);else if(a.id==='show_mains_demo')dispatch({type:'SHOW_MAINS_DEMO',device:'fridge'});else if(a.id==='show_hint')showHint();else if(a.id==='open_comparison')compare();else if(a.id==='restart')resetRequest();else if(a.id==='pick_battery')dispatch({type:'PICK_BATTERY'});}
function showHint(){dispatch({type:'REQUEST_HINT'});ask(state.language==='ar'?'أريد تلميحًا':'I need a hint');}
async function playRadio(){const rev=state.sessionRevision;if(!(await radioTune())&&rev===state.sessionRevision)dispatch({type:'AUDIO_FAILED'});if(rev!==state.sessionRevision||state.muted||state.devices.radio.status!=='running')stopAudio();}
function batteryDown(e){if(['intro','loading','recoverable_error'].includes(state.phase))return;dispatch({type:'PICK_BATTERY',mode:e.pointerType==='touch'?'touch':'drag'});drag={x:e.clientX,y:e.clientY,moved:false,pointerId:e.pointerId};}
document.addEventListener('pointermove',e=>{if(!drag)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>9)drag.moved=true;if(drag.moved){const g=$('#drag-ghost');g.hidden=false;g.style.left=e.clientX+'px';g.style.top=e.clientY+'px';}});
document.addEventListener('pointerup',e=>{if(!drag)return;const moved=drag.moved;drag=null;$('#drag-ghost').hidden=true;if(!moved)return;const el=document.elementFromPoint(e.clientX,e.clientY),target=el?.closest('[data-target]')?.dataset.target;let id=target;if(!id&&el?.closest('#scene'))id=scene?.at(e.clientX,e.clientY);if(id==='mains')dispatch({type:'DROP_ON_MAINS'});else if(config.devices.includes(id))tryDevice(id);else dispatch({type:'DROP_OUTSIDE'});},true);
document.addEventListener('pointercancel',()=>{if(drag){drag=null;$('#drag-ghost').hidden=true;dispatch({type:'CANCEL_DRAG'});}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(drag||state.batteryLocation==='held'){drag=null;pendingDevice=null;$('#drag-ghost').hidden=true;dispatch({type:'CANCEL_DRAG'});}if(state.chatOpen){dispatch({type:'TOGGLE_CHAT'});$('#chat-toggle').focus();}}});
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,c=t();switch(a){
 case 'start':dispatch({type:'START'});tutorial=true;render();break;
 case 'doneTutorial':tutorial=false;render();$('#battery-button').focus();break;
 case 'help':tutorial=true;render();break;
 case 'pick':if(state.batteryLocation!=='held')dispatch({type:'PICK_BATTERY',mode:e.detail===0?'keyboard':'click'});break;
 case 'remove':dispatch({type:'REMOVE_BATTERY'});break;
 case 'device':tryDevice(b.dataset.device);break;
 case 'predictYes':prediction(true);break;case 'predictNo':prediction(false);break;case 'predictSkip':prediction(null);break;
 case 'mains':if(state.batteryLocation==='held')dispatch({type:'DROP_ON_MAINS'});else dispatch({type:state.devices.fridge.status==='running'?'STOP_MAINS_DEMO':'SHOW_MAINS_DEMO',device:'fridge'});break;
 case 'power':dispatch({type:'TRY_POWER',device:b.dataset.device});if(b.dataset.device==='radio'&&!state.muted&&state.devices.radio.status==='running')playRadio();if(b.dataset.device==='fridge')dispatch({type:'TOGGLE_DOOR'});break;
 case 'sound':dispatch({type:'SET_MUTED',value:!state.muted});break;
 case 'listen':if(!state.muted&&!speak(state.message||c.intro,state.language))dispatch({type:'AUDIO_FAILED'});else if(state.muted){dispatch({type:'SET_MUTED',value:false});if(!speak(state.message||c.intro,state.language))dispatch({type:'AUDIO_FAILED'});}break;
 case 'stopAudio':stopAudio();break;
 case 'chat':dispatch({type:'TOGGLE_CHAT'});if(!state.chatOpen)$('#chat-toggle').focus();break;
 case 'hint':showHint();break;case 'dismissHint':dispatch({type:'DISMISS_IDLE'});break;
 case 'settings':settings();break;case 'reset':resetRequest();break;case 'confirmReset':dispatch({type:'RESET'});break;
 case 'compare':compare();break;
 case 'closeDialog':pendingDevice=null;dispatch({type:'CLOSE_COMPARISON'});closeDialog();break;
 case 'quiz':dispatch({type:'QUIZ_ANSWER',device:b.dataset.device,answer:b.dataset.answer});{const d=b.dataset.device,answer=b.dataset.answer;compare();$(`[data-action="quiz"][data-device="${d}"][data-answer="${answer}"]`)?.focus();}break;
 case 'complete':dispatch({type:'COMPLETE'});if(state.phase==='completed')completed();break;
 case 'quickQuestion':ask(b.dataset.question);break;
 case 'suggested':try{runSuggested(JSON.parse(b.dataset.suggestion));}catch{}break;
 case 'inspect':scene?.inspect(b.dataset.device);break;
 case 'zoomIn':case 'zoomOut':scene?.[a]();break;case 'resetView':scene?.reset();break;
}});
async function loadScene(){const rev=state.sessionRevision;try{const {createLabScene}=await import('./scene.js');scene=await createLabScene($('#scene'),{getState:()=>state,dispatch:e=>dispatch({...e,sessionRevision:rev}),onBattery:batteryDown,onDevice:tryDevice,projectLabel:(id,x,y)=>{const el=$('#label-'+id);if(el){if(innerWidth<=560){x=$('#scene').clientWidth*({fridge:.18,radio:.5,car:.82}[id]);y=95;}el.style.left=x+'px';el.style.top=y+'px';}}});if(scene)dispatch({type:'READY',sessionRevision:rev});}catch{dispatch({type:'RENDERER_FAILED',sessionRevision:rev});}}
shell();loadScene();resetIdle();
// Read-only diagnostics for acceptance tests. No command or rule mutation surface.
Object.defineProperty(window,'labDiagnostics',{value:()=>({state:structuredClone(state),render:scene?.stats()||null}),writable:false});
